[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ptych"
version = "0.0.1"
description = ""
readme = "README.md"
requires-python = ">=3.13,<3.14"
license = "MIT"
authors = [
    {name = "Robin Cunningham", email = "rspcunningham@gmail.com"}
]
dependencies = [
    "jaxtyping>=0.3.3",
    "numpy>=2.3.4",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "tqdm>=4.67.1",
    "matplotlib>=3.10.7",
    "seaborn>=0.13.2",
]

[tool.hatch.build.targets.wheel]
packages = ["src/ptych"]

[project.scripts]
ptych-dataset = "ptych.data.upload.cli:main"


[dependency-groups]
dev = [
    "ruff>=0.15.11",
    "ty>=0.0.31",
]

[tool.ruff.lint.per-file-ignores]
"src/ptych/**/*.py" = ["F722", "F821"]
