name: Update Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Call Update Documentation Action
      uses: rspcunningham/auto-documentator@main
      with:
        main_repo_owner: 'rspcunningham'
        main_repo_name: 'fpm-py'
        main_github_directory_path: 'fpm_py'
        docs_repo_owner: 'rspcunningham'
        docs_repo_name: 'fpm-py-docs'
        docs_github_directory_path: 'docs/reference'
        token: ${{ secrets.DOCS_EDITOR }}